spring:
  data:
    mongodb:
      host: localhost
      port: 27017
      database: customer_service
#      username: victor
#      password: victor
      authentication-database: admin
    redis:
      host: localhost
      port: 6379

server:
  port: 8010


